spring.application.name=demo


management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=My Cool app
info.app.description=Seriously this is a really cool app 
info.app.version=1.0.0

spring.security.user.name=admin
spring.security.user.password=Password!

logging.file.name=logs/app.log 

logging.level.com.spring.demo=WARN
logging.logback.rollingpolicy.file-name-pattern=logs/app.%d{yyyy-MM-dd}.%i.log.gz
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# leaving this commented out for now
# we should make sure our app with all beans loaded has enough ram 
# before we do any optimizations like this
#spring.main.lazy-initialization=true

spring.datasource.url=jdbc:postgresql://localhost:5432/student_tracker
spring.datasource.username=chinook
spring.datasource.password=password

# NONE OF THESE ARE A REPLACEMENT FOR A FULL MIGRATION TOOL LIKE FLYWAY
# THESE ARE GOOD FOR PROTOTYPING 
# this makes hibernate try and update the db schema to match
# our entities on the server side
spring.jpa.hibernate.ddl-auto=update

# don't modify anything. just check whether the existing schema matches my mappings
#spring.jpa.hibernate.ddl-auto=validate

# drop and recreate the schema every time the application starts
#spring.jpa.hibernate.ddl-auto=create

# create the schema on startup and drops it when the application shuts down
#spring.jpa.hibernate.ddl-auto=create-drop