CREATE DATABASE student_tracker;

-- Change to student_tracker db and then run the rest
--
-- Table structure for table student
--

DROP TABLE IF EXISTS student;

CREATE TABLE student (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name varchar(45) DEFAULT NULL,
  last_name varchar(45) DEFAULT NULL,
  email varchar(45) DEFAULT NULL
);